version: '3.8'
services:
  backend:
    build:
      context: ./backend/ShareIt  # Adjust this path to the location of your backend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5000:8080"  # Maps port 5000 on the host to port 8080 in the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Set the environment to Development for debugging purposes

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile  
    ports:
      - "80:80"  # Maps port 80 on the host to port 80 in the container, adjust if necessary
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000  # Environment variable for the backend URL, adjust if necessary