version: '3.8'
services:
  backend:
    build:
      context: ./backend/ShareIt  # Adjust this path to the location of your backend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5000:8080"  # Maps port 5000 on the host to port 8080 in the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Set the environment to Development for debugging purposes

# TODO
# Configure the frontend service